mountain-sailors/stock-battle-server

.gitignore
package-lock.json
package.json
src/app.ts
src/models/index.ts

close #4 
- Should create 'stock_battle' database

[FEAT] DB Connection

---

.eslintrc.json
src/@types/dataType.ts
src/models/index.ts

[REFACTOR] Make DB connection with AWS RDS #7

---

src/@types/WinConditionType.ts
src/models/Room.ts
src/models/Stock.ts
src/models/User.ts
src/models/UserGameHistory.ts
src/models/UserStock.ts

close #5 
- 연동된 AWS RDS 데이터 베이스에 테이블 생성됨

[FEAT] Model

---

.eslintrc.json
jest.config.js
nodemon.json
package-lock.json
package.json
src/app.ts
src/server.ts
src/tests/any.test.ts

close #29 
- `npm run test` 하면 테스트 코드가 실행됩니다.
- 일부 app.js 에 있는 코드를 server.js 로 분리한 이유는 서버를 실질적으로 실행하는 부분이랑 jest가 충돌해 에러가 나기 때문에 해당 부분들을 분리시켰습니다.

[TEST] Jest setting #29

---

logs/.2175ca2113711a4fb9c5cf33852ebfa9969e83f3-audit.json
logs/.ba81331cb9d70de713aa7edad0bae69ac43bb076-audit.json
logs/2021-11-09.log
package-lock.json
package.json
src/config/logger.ts
src/models/index.ts
src/server.ts

close #15
- 일단 로그 파일의 최대 크기를 20mb로 설정해놓았고, 로그 파일을 14일 간만 보관할 수 있게 적용했습니다. 혹시 다른 의견 있으시면 댓글 남겨주세요.
- 로그 관련 내용을 노션에 올려 놓을 테니 한번 확인해주세요.

[FEAT] Winston Setting

---

package-lock.json
package.json
src/auth/passport.ts
src/controllers/userController.ts
src/models/User.ts
src/routes/userRouter.ts
src/services/userService.ts
tests/user.test.ts

close #40
- 현재 DB에 저장 되어 있는 것들은 비밀번호가 bcrypt가 적용 되어 있지 않아 패스워드 비교하는 단계에서 암호화된 패스워드와 비교하기 때문에 오류가 발생할 수 있습니다. merge 하고 나서 바로 User table 에 있는 것 모두 삭제하고 만들어 놓은 걸로 import 할게요!

[TEST] User API tests, error handling and bcrypt

---

src/controllers/userStockController.ts
src/services/userStockService.ts
tests/userStock.test.ts

[TEST] Test code for user stock API & Error handling #42

---

src/controllers/userGameHistoryController.ts
tests/userGameHistory.test.ts

close #48
- 이 API를 호출할 때 유저 정보도 어차피 같이 호출할 것 같기도 하고 GET METHOD 라 큰 문제는 되지 않을 것 같아서 따로 userId 가 있는지 체크해서 처리하지는 않았습니다.
- 잘 생각이 안나는데 그 외에 예외 처리가 필요한 부분이 있으면 알려주세요~

[TEST] UserGameHistory API test

---

src/app.ts
src/controllers/stockController.ts
src/jobs/stockScheduler.ts
tests/stock.test.ts

close #50
- 테스트 좀 해보고 싶어서 스케줄러들이 작동하게 만들었고 주식은 아직 무료 API 를 쓰고 있어서 계속 돌리면 안될 것 같아 일단 5분에 한번으로 해놨습니다,,
- merge 하고 나면 AWS 서버에 바로 적용해서 돌릴게요

[TEST] Tests for stock API

---

src/controllers/dashboardController.ts
src/controllers/playerController.ts
src/game/gameData.ts
src/routes/index.ts
src/routes/playerRouter.ts
src/services/playerService.ts
src/services/roomService.ts
swagger/swagger.yaml

close #52 
- bug reports에 있는대로 profit type이 string이여서 해당 부분 수정했고 rank도 type 확인해봤는데 number 여서 수정하지 않았음

[FEAT] Players Info API and fix some bugs

---

src/controllers/userGameHistoryController.ts
src/routes/userGameHistoryRouter.ts
src/services/userGameHistoryService.ts
swagger/swagger.yaml

close #54
- 현재 user game history 에 데이터가 많지 않아 테스트를 충분히 해보지는 못했습니다. 다음에 데이터가 많이 쌓이면 테스트 해봅시다.

[FEAT] Game Result API

---

src/services/playerService.ts
src/utils/stocks.ts

[FIX] Add color to playerInfo API response & add more stock data

---

appspec.yml
buildspec.yml
initialize.sh
start.sh

close #34 
- codepipeline과 연결시킬 예정

[FEAT] Add yml files for AWS ci/cd

---

src/services/dashboardService.ts

[FIX] SSE improvement #62

---

src/game/startGame.ts
src/models/UserStock.ts

[FIX] Stock amount type and cancelRoom

---

src/controllers/dashboardController.ts
src/game/calculator.ts
src/game/endGame.ts
src/game/gameData.ts
src/services/dashboardService.ts
src/services/roomService.ts

[REFACTOR] SSE initial data

---

src/auth/passport.ts
src/controllers/meController.ts
src/controllers/playerController.ts
src/controllers/roomController.ts
src/controllers/userGameHistoryController.ts
src/jobs/gameScheduler.ts
src/server.ts

[FIX] Use logger instead of console.log

---

src/controllers/roomController.ts
src/routes/roomRouter.ts
swagger/swagger.yaml

[FEAT] room 한 개에 대한 정보 제공 API

---

package-lock.json
package.json
src/controllers/userController.ts
src/models/User.ts
src/routes/userRouter.ts
src/services/roomService.ts
src/services/userService.ts
src/utils/generateInvitationCode.ts
src/utils/generateVerificationCode.ts
swagger/swagger.yaml

[FIX] Email verification & update password

---

initialize.sh
start.sh

close #71 
- 스크립트 문제가 아닐수도 있어서 이 브랜치에서 계속 머지시키면서 테스트해봐야할 것 같습니다.

[hotfix] Fix CI/CD

---

appspec.yml
buildspec.yml
initialize.sh
start.sh

[hotfix] cicd permission

---

initialize.sh
src/controllers/userController.ts
src/routes/userRouter.ts
src/services/userService.ts
start.sh
swagger/swagger.yaml

[FEAT] Username validation

---

src/services/userService.ts

[Hotfix] Change nodemailer options

---

src/controllers/oauthController.ts
src/models/User.ts
src/routes/index.ts
src/routes/oauthRouter.ts
src/services/oauthService.ts
src/utils/generateUsername.ts

- add /oauth/naver
- add /oauth/kakao
- add column 'type' to 'user' table
- add random username generator
close #80 
- user 테이블 수정 (type 컬럼 추가)
- .env 파일은 노션에 올렸습니다.

[FEAT] Add Naver, Kakao Login #80
